{
  "id":167,
  "name":"migxcalendar_loadcontainer",
  "formtabs":[
    {
      "MIGX_id":1,
      "caption":"[[%migxcal.search]]",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":1,
          "field":"search",
          "caption":"[[%migxcal.search]]",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"migxcalendars_livesearchevent",
          "validation":"",
          "configs":"",
          "restrictive_condition":"",
          "display":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        }
      ]
    }
  ],
  "contextmenus":"",
  "actionbuttons":"",
  "columnbuttons":"",
  "filters":"[]",
  "extended":{
    "migx_add":"",
    "formcaption":"",
    "update_win_title":"",
    "win_id":"migxcalendar_loadcontainer",
    "maxRecords":"",
    "addNewItemAt":"bottom",
    "multiple_formtabs":"",
    "actionbuttonsperrow":4,
    "winbuttonslist":"",
    "extrahandlers":"",
    "filtersperrow":4,
    "packageName":"migxcalendars",
    "classname":"migxCalendarEvents",
    "task":"loadcontainer",
    "getlistsort":"",
    "getlistsortdir":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"",
    "has_jointable":"yes",
    "getlistwhere":"",
    "joins":[
      {
        "alias":"Category"
      }
    ],
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":"",
    "winbuttons":[
      {
        "button":"cancel"
      },
      {
        "button":"migxcalloaddatecontainer"
      }
    ],
    "onsubmitsuccess":"",
    "submitparams":""
  },
  "columns":"[]",
  "createdby":8,
  "createdon":"2014-03-21 15:50:59",
  "editedby":1,
  "editedon":"2014-03-26 07:51:12",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"2014-03-21 01:00:00",
  "publishedby":0
}